server.port=8098

application.name=eeutil-igae

eeutil-rest-igae.http.auth-token-header-name=X-API-token
eeutil-rest-igae.http.auth-token=123454321

logging.file=eeutil-rest-igae.log

server.servlet.context-path=/eeutil-igae

logging.config=file:${eeutil-igae.config.path}/logback.xml


#parametros de javamelody
#javamelody.enabled=false
#javamelody.init-parameters.authorized-users: javamelody:jm123
#javamelody.init-parameters.monitoring-path=/admin/monitoring
#fin parametros javamelodyserver.port=8098

application.name=eeutil-igae

eeutil-rest-igae.http.auth-token-header-name=X-API-token
eeutil-rest-igae.http.auth-token=123454321

logging.file=eeutil-rest-igae.log

server.servlet.context-path=/eeutil-igae

logging.config=file:${eeutil-igae.config.path}/logback.xml


#parametros de javamelody
#javamelody.enabled=false
#javamelody.init-parameters.authorized-users: javamelody:jm123
#javamelody.init-parameters.monitoring-path=/admin/monitoring
#fin parametros javamelody